services:
    db:
        image: mysql:latest
        container_name: mysql_db
        restart: unless-stopped
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - "${DB_PORT}:3306"

    pma:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "8888:80"
